PREFIX base: <http://kg-course.io/health/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (COUNT(?patient) AS ?numDuplicateDiseases)
WHERE {
  SELECT ?patient ?disease (COUNT(?disease) AS ?num)
  WHERE {
    ?patient rdf:type base:Patient .
    ?patient base:hasDisease ?disease .
  }
  GROUP BY ?patient ?disease
  HAVING (?num > 1)
}