PREFIX base: <http://kg-course.io/health/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (COUNT(?patient) AS ?numDuplicatedPatients)
WHERE {
  SELECT ?patient
  WHERE {
    ?patient rdf:type base:Patient .
  }
  GROUP BY ?patient
  HAVING (COUNT(?patient) > 1)
}