PREFIX base: <http://kg-course.io/health/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (COUNT(?measurement) AS ?numIncorrectType)
WHERE {
  ?measurement rdf:type base:ClinicalMeasurement .
  ?measurement base:value ?value .

  BIND(xsd:float AS ?expectedType)
  BIND(datatype(?value) AS ?actualType)

  FILTER(?actualType != ?expectedType)
}